version: '3'

services:
  whatsapp-http-api_waha:
    image: devlikeapro/whatsapp-http-api
    container_name: whatsapp-http-api_waha
    ports:
      - "7710:3000/tcp"
    environment:
      # Environment variables from https://waha.devlike.pro/docs/how-to/config/
      - WHATSAPP_HOOK_URL=https://httpbin.org/post
      - WHATSAPP_HOOK_EVENTS=message
      - WHATSAPP_DEFAULT_ENGINE=WEBJS
    restart: always

