service: caloteiros-service
frameworkVersion: '3'

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-offline-watcher

custom:
  useDotenv: true
  serverless-offline:
    httpPort: 4000
  serverless-offline-watcher:
    - path:
        - src/**/*.ts
      command: echo "Getted an update, refreshing..."

provider:
  name: aws
  runtime: nodejs18.x

package:
  individually: true

functions:
  service:
    handler: src/controllers/service-owner/register-service-owner.handler
    events: 
      - http:
          path: service/register
          method: post
          
