service: caloteiros-service
frameworkVersion: '3'

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-offline-watcher

custom:
  useDotenv: true
  serverless-offline:
    httpPort: 4000
  serverless-offline-watcher:
    - path:
        - src/**/*.ts
      command: echo "Getted an update, refreshing..."

provider:
  name: aws
  runtime: nodejs18.x

package:
  individually: true

functions:
  admin-register:
    handler: src/controllers/service-owner/register-service-owner.handler
    events: 
      - http:
          path: admin/register
          method: post
  charge-register:
    handler: src/controllers/charge/register-charge.handler
    events: 
      - http:
          path: charge/register
          method: post
  charge-add-team:
    handler: src/controllers/charge/register-team-to-charge.handler
    events: 
      - http:
          path: charge/{id}/add-team
          method: post
  charge-call:
    handler: src/controllers/charge/send-message-to-team.handler
    events: 
      - http:
          path: charge/{id}/call
          method: post
          
